# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  cli:
    cmds:
      - docker compose run --rm yoloplay bash
    silent: true
